version: '3.7'

services:
  reisdocumenten-data-service:
    container_name: reisdocumenten-data-service
    image: ghcr.io/brp-api/reisdocumenten-data-service:latest
    environment:
      - ASPNETCORE_URLS=http://+;
      - Database__Host=postgres
      - Database__Username=root
      - Database__Password=root
      - Database__Database=rvig_haalcentraal_testdata
      - HaalcentraalApi__MaxSearchResults=10
      - ProtocolleringAuthorization__UseAuthorizationChecks=false
      - ProtocolleringAuthorization__UseProtocollering=false
      - Ecs__Path=/var/log/reisdocumenten-data-service.json
      - Ecs__SecuredPath=/var/log/reisdocumenten-data-service-secured.json
      - Ecs__FileSizeLimitBytes=1073741824
      - Ecs__RetainedFileCountLimit=10
      - Serilog__MinimumLevel__Default=Warning
      - Serilog__MinimumLevel__Override__Serilog=Information
    ports:
      - "8000:80"
    volumes:
      - ../test-data/logs:/var/log
    networks:
      - brp-api-network

networks:
  brp-api-network:
   name: brp-api-network
